create database niceshoesshop;

use niceshoesshop;

CREATE TABLE PRODUCT_LIST (
	ID INT PRIMARY KEY AUTO_INCREMENT,
    PRODUCT_NAME VARCHAR(20),
    PRODUCT_CODE VARCHAR(10),
    PRODUCT_DESCRIPTION VARCHAR(40),
    GENDER CHAR(1)
);

CREATE TABLE COLORS (
COLOR_ID INT NOT NULL AUTO_INCREMENT,
COLOR VARCHAR(20),
PRIMARY KEY (COLOR_ID)
);

CREATE TABLE PRODUCT_COLORS (
	PRODUCT_ID INT,
    COLOR_ID INT,
    foreign key (PRODUCT_ID) references PRODUCT_LIST(ID),
    foreign key (COLOR_ID) references COLORS(COLOR_ID)
);

ALTER TABLE PRODUCT_LIST ADD COLUMN PRICE INT NOT NULL;

ALTER TABLE PRODUCT_LIST DROP COLUMN PRODUCT_DESCRIPTION;

CREATE TABLE SIZES (
SIZE_ID INT PRIMARY KEY AUTO_INCREMENT,
SIZE_TIPE CHAR(1),
SIZE_CODE  VARCHAR(6)
);

CREATE TABLE PRODUCT_SIZES (
PRODUCT_ID INT,
SIZE_ID INT,
foreign key (PRODUCT_ID) references PRODUCT_LIST(ID),
foreign key (SIZE_ID) references SIZES(SIZE_ID)
);

CREATE TABLE PAYMENT (
ID_PAYMENT_METHOD INT PRIMARY KEY AUTO_INCREMENT,
PAYMENT_METHOD VARCHAR(10)
);

CREATE TABLE PRODUCT_RETURN (
RETURN_ID INT PRIMARY KEY AUTO_INCREMENT,
RETURN_NR INT,
NR_DAYS_RETURN_PAYMENT INT,
COST_RETURN_TRANSPORT INT
);

CREATE TABLE ORDE (
ORDE_ID INT PRIMARY KEY AUTO_INCREMENT,
ORDE_CODE VARCHAR(10),
ORDE_DATE DATE,
NUME VARCHAR(20),
PRENUME VARCHAR(20),
ADRESA VARCHAR(40)
);

CREATE TABLE ORDE_PRODUCT (
ORDE_ID INT,
PRODUCT_ID INT,
QUANTITY INT,
DISCOUNT int,
foreign key (PRODUCT_ID) references PRODUCT_LIST(ID),
foreign key (ORDE_ID) references ORDE(ORDE_ID)
);

INSERT INTO PRODUCT_LIST (PRODUCT_NAME, PRODUCT_CODE, GENDER, PRICE) 
VALUES ('Nike Air Max', 'P189K', 'M', '400'),
('Adidas Ultraboost', 'P211L', 'M', '350');

SELECT * FROM PRODUCT_LIST;

DELETE FROM PRODUCT_LIST WHERE ID='1';

ALTER TABLE PRODUCT_LIST DROP COLUMN PRODUCT_DESCRIPTION;
